project_name = "NewsForgeAI"
project_version = "0.1.0"
log_level = "INFO"
listen_host = "0.0.0.0"
listen_port = 8080

[app]
api_key = ""
max_concurrent_tasks = 5
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
endpoint = ""
video_llm_provider = "gemini"

[azure]
speech_key = ""
speech_region = ""
speech_endpoint = ""

[proxy]
http_proxy = ""
https_proxy = ""